id: PDA872448
initial_creation_type: ocr
source_metadata:
  volumes:
    476b7bd6a38d46028c5ef5002574ec08:
      base_file: v065.txt
      image_group_id: I1PD95910
      title: བྱང་ཆུབ་ཏུ་སེམས་བསྐྱེད་པའི་ཆོ་ག།
      total_pages: 1498
      volume_number: 65
